/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scripts.chinner_GUI;

import javax.swing.table.DefaultTableModel;

import org.tribot.api.General;

import scripts.Chinner;
import scripts.chinner_utilities.Constants;
import scripts.chinner_utilities.Variables;

/**
 *
 * @author joel_
 */
public class ChinningGUI extends javax.swing.JFrame {

	/**
	 * Creates new form ChinningGUI
	 */
	public ChinningGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		potionType = new javax.swing.JComboBox<>();
		jLabel5 = new javax.swing.JLabel();
		potionAmount = new javax.swing.JTextField();
		bAdd = new javax.swing.JButton();
		bDelete = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablePotions = new javax.swing.JTable();
		jPanel6 = new javax.swing.JPanel();
		jLabel17 = new javax.swing.JLabel();
		combatStyle = new javax.swing.JComboBox<>();
		jLabel6 = new javax.swing.JLabel();
		amountChins = new javax.swing.JTextField();
		typeChin = new javax.swing.JComboBox<>();
		jLabel7 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		lvlRangePot = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		foodType = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		amountFood = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		mSpeed = new javax.swing.JSlider();
		startButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(204, 0, 0));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Volcom3d's Chinner");

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Potions",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 14))); // NOI18N
		jPanel5.setToolTipText("");
		jPanel5.setName(""); // NOI18N

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel4.setText("Potion: ");

		potionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ranging potion (4)",
				"Prayer potion (4)", "Antipoison (4)", "Antidote++ (4)", "Super antipoison(4)" }));
		potionType.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				potionTypeActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel5.setText("Amount:");

		potionAmount.setText("1");

		bAdd.setText("Add");
		bAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bAddActionPerformed(evt);
			}
		});

		bDelete.setText("Delete");
		bDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bDeleteActionPerformed(evt);
			}
		});

		tablePotions.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { "Prayer potion (4)", "15" },
				{ "Antidote++ (4)", "1" }, { "Ranging potion (4)", "4" } }, new String[] { "Potion", "Amount" }));
		jScrollPane1.setViewportView(tablePotions);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap().addGroup(jPanel5Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
						.addGroup(jPanel5Layout.createSequentialGroup().addComponent(jLabel4)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(potionType, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel5)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(potionAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel5Layout.createSequentialGroup().addComponent(bAdd)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(bDelete)))
						.addContainerGap()));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap().addGroup(jPanel5Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
								.addComponent(potionType, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5).addComponent(potionAmount,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(bAdd).addComponent(bDelete))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addContainerGap()));

		jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Combat",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 14))); // NOI18N

		jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel17.setText("Combat style index:");

		combatStyle.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Short fuse", "Medium fuse", "Long fuse" }));

		jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel6.setText("Amount of chins to take:");

		amountChins.setText("1500");

		typeChin.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Red chinchompa", "Gray chinchompa", "Black chinchompa" }));
		typeChin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				typeChinActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel7.setText("Type of chins:");

		jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel9.setText("Drink range pot at:");

		lvlRangePot.setText("82");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout
						.createSequentialGroup().addContainerGap().addGroup(jPanel6Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(
												jPanel6Layout.createSequentialGroup().addComponent(jLabel6)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(amountChins))
										.addGroup(jPanel6Layout.createSequentialGroup().addComponent(jLabel17)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(combatStyle, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel6Layout.createSequentialGroup().addComponent(jLabel7)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(typeChin, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)))
								.addGroup(jPanel6Layout.createSequentialGroup().addComponent(jLabel9)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lvlRangePot, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel17).addComponent(combatStyle,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel7).addComponent(typeChin, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(amountChins, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel9).addComponent(lvlRangePot, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Healing",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 14))); // NOI18N
		jPanel4.setToolTipText("");
		jPanel4.setName(""); // NOI18N

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel2.setText("Food:");

		foodType.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Monkfish", "Lobster", "Shark", "Trout", "Tuna potato", "Dark crab", "Anglerfish" }));
		foodType.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				foodTypeActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel3.setText("Amount:");

		amountFood.setText("3");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
										foodType, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(amountFood)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(foodType, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(amountFood, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(17, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addContainerGap()));

		jTabbedPane1.addTab("General", jPanel1);

		jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel8.setText("Mouse speed:");

		mSpeed.setMajorTickSpacing(50);
		mSpeed.setMaximum(150);
		mSpeed.setMinimum(50);
		mSpeed.setMinorTickSpacing(5);
		mSpeed.setPaintLabels(true);
		mSpeed.setPaintTicks(true);
		mSpeed.setSnapToTicks(true);
		mSpeed.setValue(100);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(jLabel8)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(mSpeed, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(270, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(mSpeed, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel8))
						.addContainerGap(214, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Advanced", jPanel3);

		startButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		startButton.setText("Start");
		startButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				startButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(149, 149, 149).addComponent(jLabel1)
						.addContainerGap(150, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addContainerGap().addComponent(jTabbedPane1).addContainerGap())));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
						.addComponent(startButton,
								javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(53, 53, 53)
								.addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(63, Short.MAX_VALUE))));

		pack();
	}// </editor-fold>

	private void potionTypeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void bAddActionPerformed(java.awt.event.ActionEvent evt) {
		DefaultTableModel model = (DefaultTableModel) tablePotions.getModel();
		model.addRow(new Object[] { potionType.getSelectedItem().toString(), potionAmount.getText() });
	}

	private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {
		DefaultTableModel model = (DefaultTableModel) tablePotions.getModel();
		if (tablePotions.getSelectedRow() != -1) {
			model.removeRow(tablePotions.getSelectedRow());
		}
	}

	private void foodTypeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void typeChinActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < tablePotions.getRowCount(); i++) {
			String pot = tablePotions.getModel().getValueAt(i, 0).toString();
			Integer number = Integer.valueOf(tablePotions.getModel().getValueAt(i, 1).toString());
			if (pot.equals("Prayer potion (4)")) {
				Variables.NUMBER_PRAY_POT = number;
			} else if (pot.equals("Antipoison (4)")) {
				Variables.SELECTED_POISON_POT = Constants.ANTIPOISON_POT;
				Variables.NUMBER_POISON_POT = number;
			} else if (pot.equals("Super antipoison (4)")) {
				Variables.SELECTED_POISON_POT = Constants.SUPER_ANTIPOISON_POT;
				Variables.NUMBER_POISON_POT = number;
			} else if (pot.equals("Ranging potion (4)")) {
				Variables.NUMBER_RANGING_POT = number;
			} else if (pot.equals("Antidote++ (4)")) {
				Variables.SELECTED_POISON_POT = Constants.ANTIDOTEPP_POT;
				Variables.NUMBER_POISON_POT = number;
			}
		}

		General.println("Number pray pots: " +Variables.NUMBER_PRAY_POT);
		General.println("Number select poison cure pots: " +Variables.NUMBER_POISON_POT);
		General.println("Number ranging pots: " +Variables.NUMBER_RANGING_POT);
		
		String cbStyle = combatStyle.getSelectedItem().toString();
		if (cbStyle.equals("Short fuse")) {
			Variables.SELECTED_COMBAT_STYLE = 0;
		} else if (cbStyle.equals("Medium fuse")) {
			Variables.SELECTED_COMBAT_STYLE = 1;
		} else if (cbStyle.equals("Long fuse")) {
			Variables.SELECTED_COMBAT_STYLE = 2;
		}
		General.println("Combat style index: " +Variables.SELECTED_COMBAT_STYLE);

		String chinType = typeChin.getSelectedItem().toString();
		if (chinType.equals("Red chinchompa")) {
			Variables.SELECTED_CHINS = Constants.RED_CHINCHOMPA;
		} else if (chinType.equals("Gray chinchompa")) {
			Variables.SELECTED_CHINS = Constants.GRAY_CHINCHOMPA;
		} else if (chinType.equals("Black chinchompa")) {
			Variables.SELECTED_CHINS = Constants.BLACK_CHINCHOMPA;
		}
		General.println("Selected chin ID: " +Variables.SELECTED_CHINS);

		Variables.AMOUNT_CHINS = Integer.valueOf(amountChins.getText());
		General.println("Amount chins: " +Variables.AMOUNT_CHINS);
		Variables.DRINK_RANGE_POT_AT = Integer.valueOf(lvlRangePot.getText());
		General.println("Drink pray pot at lvl: " +Variables.DRINK_RANGE_POT_AT);
		String food = foodType.getSelectedItem().toString();
		if (food.equals("Monkfish")) {
			Variables.SELECTED_FOOD = Constants.MONKFISH;
		} else if (food.equals("Shark")) {
			Variables.SELECTED_FOOD = Constants.SHARK;
		} else if (food.equals("Lobster")) {
			Variables.SELECTED_FOOD = Constants.LOBSTER;
		} else if (food.equals("Trout")) {
			Variables.SELECTED_FOOD = Constants.TROUT;
		} else if (food.equals("Tuna potato")) {
			Variables.SELECTED_FOOD = Constants.TUNA_POTATO;
		} else if (food.equals("Dark crab")) {
			Variables.SELECTED_FOOD = Constants.DARK_CRAB;
		} else if (food.equals("Anglerfish")) {
			Variables.SELECTED_FOOD = Constants.ANGLERFISH;
		}
		General.println("Food ID: " +Variables.SELECTED_FOOD);
		Variables.NUMBER_FOOD = Integer.valueOf(amountFood.getText());
		General.println("Number food: " +Variables.NUMBER_FOOD);
		Variables.MOUSE_SPEED = Integer.valueOf(mSpeed.getValue());
		General.println("Mouse speed: " + Variables.MOUSE_SPEED);
		
		Chinner.waitGUI=false;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ChinningGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ChinningGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ChinningGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ChinningGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChinningGUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JTextField amountChins;
	private javax.swing.JTextField amountFood;
	private javax.swing.JButton bAdd;
	private javax.swing.JButton bDelete;
	private javax.swing.JComboBox<String> combatStyle;
	private javax.swing.JComboBox<String> foodType;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField lvlRangePot;
	private javax.swing.JSlider mSpeed;
	private javax.swing.JTextField potionAmount;
	private javax.swing.JComboBox<String> potionType;
	private javax.swing.JButton startButton;
	private javax.swing.JTable tablePotions;
	private javax.swing.JComboBox<String> typeChin;
	// End of variables declaration
}
