package scripts.zulrahUtilities;

public enum BankingState {
	TELEPORTING, WALKTOBANK, TAKEOUTROR, OPENBANK1, PUTROR, OPENBANK2, WITHDRAWITEMS, WALKTOPORT, TELEZUL, GOTOZUL, CLICK_BOAT, TELECAMELOT, WALKPORT, CLICKCHARTER, WALKTOZUL
}
